### ISSUE TITLE
Docstring for create_system_of_bodies is missing

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-multidoc#10]
It is not in the yaml files.

**Comment by DominicDirkx** [comment]
Corrected; new API docs is building:

https://readthedocs.org/projects/tudatpy/builds/

**Comment by FilippoOggionni** [comment]
Once it has built, if you have time, an intersphinx link should be added in this [page](https://tudat-space.readthedocs.io/en/latest/_src_user_guide/state_propagation/environment_setup/create_bodies/create_bodies_from_settings.html#create-bodies-from-settings) to solve the TODO.

**Comment by DominicDirkx** [comment]
Thanks for the reminder. Page modified, and ready to push :)

**Comment by DominicDirkx** [comment]
Done and pushed!

**Comment by DominicDirkx** [comment]
Entry and link confirmed to be working
