### ISSUE TITLE
Correct API Documentation for empirical acceleration

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-multidoc#12]
@FilippoOggionni there is a mistake (conceptual, not typo) in the documentation of the empirical acceleration (and the code example. 
The acceleration is no longer "self-exerted", but registered as coming from the central body. 
I don't wanna mess with your docstrings without permission, so please assign that task to me if I have the go on making the modifications.

**Comment by DominicDirkx** [comment]
Great that you spotted this! If @FilippoOggionni is fine with it, go ahead and push the correction

**Comment by FilippoOggionni** [comment]
Yeah, nice that you spotted it! I was not aware of this change.

Please go ahead and fix it (I don't consider them "my docstrings" anymore... 😄)

**Comment by jo11he** [comment]
I am still going to take care of this!

**Comment by FilippoOggionni** [comment]
I see that this has been taken care of (it is already [online](https://tudatpy.readthedocs.io/en/latest/acceleration.html#tudatpy.numerical_simulation.propagation_setup.acceleration.empirical)), so I will close this!
