### ISSUE TITLE
Writing API for MGA-DSM

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat-multidoc#14]
- [x] Writing API for MGA-DSM code
- [x] Insert docstrings in tudatpy

Repo: https://github.com/MiguelAvillez/tudat-multidoc

**Comment by MiguelAvillez** [comment]
Pull request for adding docstrings to tudatpy: https://github.com/tudat-team/tudatpy/pull/25

**Comment by jo11he** [comment]
Hi @MiguelAvillez! Great Job on the docstrings, a really nice addition. I had a look at the new functionality, out of curiosity, so I visited the API docs and have 2 comments: 
1. I guess the mga and dsm abbreviations stand for multi-gravity assist and deep space manoeuvre and I think it would be nice if the term multi-gravity assist appeared in the extended descriptions of the function "mga_transfer_settings", similar to the way that "deep space manoeuvre" is mentioned in the description of e.g. dsm_position_based_leg()
2. the enums in your module don't seem to render correctly - for comparison see[ here ](https://tudatpy.readthedocs.io/en/latest/gravity_field.html#tudatpy.numerical_simulation.environment_setup.gravity_field.GravityFieldType)

**Comment by FilippoOggionni** [comment]
@DominicDirkx just checking, have you already reviewed this?

**Comment by MiguelAvillez** [comment]
> Hi @MiguelAvillez! Great Job on the docstrings, a really nice addition. I had a look at the new functionality, out of curiosity, so I visited the API docs and have 2 comments:
> 
> 1. I guess the mga and dsm abbreviations stand for multi-gravity assist and deep space manoeuvre and I think it would be nice if the term multi-gravity assist appeared in the extended descriptions of the function "mga_transfer_settings", similar to the way that "deep space manoeuvre" is mentioned in the description of e.g. dsm_position_based_leg()
> 2. the enums in your module don't seem to render correctly - for comparison see[ here](https://tudatpy.readthedocs.io/en/latest/gravity_field.html#tudatpy.numerical_simulation.environment_setup.gravity_field.GravityFieldType)

Hi Jonas. Thanks for the feedback!
1. Good point
2. I think that happens because I added a "description" to the enum members, which I now see isn't done for any of the other enums in the API. So is the general policy to not add descriptions to the enum members? Or otherwise, should it be done with some keyword other than "description"?

**Comment by DominicDirkx** [comment]
Hi guys, I was under the impression that I had merged this already, but it must have slipped my mind, and I was thinking about the user guide. I propose we resolve the two points raised by @jo11he, and then merge this. The points seem quite minor, and should be done quickly. @MiguelAvillez, could you take care of this, or can you no longer write any hours? An example of where the enums are described in the API is here:
https://tudatpy.readthedocs.io/en/latest/propagator.html?highlight=encke#tudatpy.numerical_simulation.propagation_setup.propagator.TranslationalPropagatorType
The rendering is not ideal (yet), but it'll do :)

**Comment by MiguelAvillez** [comment]
Hi @DominicDirkx,
Actually you did merge it already (https://github.com/tudat-team/tudat-multidoc/commit/c57996cdd365976cee65a0c2993e0b39034664fc)

> The points seem quite minor, and should be done quickly. @MiguelAvillez, could you take care of this, or can you no longer write any hours? An example of where the enums are described in the API is here:
https://tudatpy.readthedocs.io/en/latest/propagator.html?highlight=encke#tudatpy.numerical_simulation.propagation_setup.propagator.TranslationalPropagatorType

I can't write any more hours but I'll do it, it only takes a few minutes.
I commented the enums the same way it is done in that TranslationalPropagatorType example... so I don't need to make any change regarding that point, right?

**Comment by DominicDirkx** [comment]
Hi Miguel, thanks! I really appreciate it :) For the enums, could you add a link (or reference) to the mathematical formulation for the DSM types? When we have those, we can officially close all the issues related to this. Many thanks to both you and @MaartenvNistelrooij for the cool conributions to Tudat!

**Comment by MiguelAvillez** [comment]
Done, cheers!
