### ISSUE TITLE
Request for an API docs update

### ISSUE THREAD

**Issue by sbcowan** [tudat-team/tudat-multidoc#16]
[The API reference](https://tudatpy.readthedocs.io/en/latest/propagator.html#tudatpy.numerical_simulation.propagation_setup.propagator.translational) does not specify what coordinates to use for the 'initial_state' argument in the propagator settings definition. A mismatch arises if you give the ‘initial_state’ in Keplerian coordinates and the propagator is in non-Keplerian coordinates. The initial state is always to be given in Cartesian coordinates w.r.t. the central body.

**Comment by FilippoOggionni** [comment]
Hi @sbcowan, thanks for posting this. I fixed it, also adding that the reference frame orientation. 
Due to some temporary issues with the API reference system, it won't show immediately on the website, but it will appear later.
