### ISSUE TITLE
Add module descriptions to API

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-multidoc#2]
Modules that still need descriptions (the ones not mentioned are done):

- [x]   environment (to be revised, currently not very clear to me)
- [x]   propagation (to be revised, currently not very clear to me)
- [x]   math (empty)
- [x]   util (empty)
- [x]   plotting (empty)

**Comment by jo11he** [comment]
This issue looks pretty advanced to me, is this maybe already closed?

**Comment by FilippoOggionni** [comment]
Modules that still need descriptions (the ones not mentioned are done):

- [ ] `environment` (to be revised, currently not very clear to me)
- [ ] `propagation` (to be revised, currently not very clear to me)
- [ ] `math` (empty)
- [ ] `util` (empty)
- [ ] `plotting` (empty)

I removed Geoffrey and assigned myself. Once it is done, I will ask @DominicDirkx to review the module descriptions.

**Comment by FilippoOggionni** [comment]
@DominicDirkx not sure if you have time to take care of this in the next days, but it should be something very quick to do. Otherwise I will do it

**Comment by DominicDirkx** [comment]
@FilippoOggionni if you could take care of this, that'd be great

**Comment by FilippoOggionni** [comment]
Now each module and submodule have at least one between ``summary`` and ``extended_summary``. I pushed the changes and triggered a new build of the API docs, which should be online soon. I will close the issue and move it to review.

@DominicDirkx could you please quickly review these for all modules and, if needed, make the necessary changes?

**Comment by FilippoOggionni** [comment]
@DominicDirkx reminder about this 🙂
