### ISSUE TITLE
Add "copy" button to example code snippets 

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-multidoc#20]
This is currently available in tudat-space, but not in the API reference.

**Comment by gaffarelj** [comment]
This issue has been resolved by adding the `sphinx_copybutton` package to the documentation. This has been implemented in commits [945fc79](https://github.com/tudat-team/tudatpy/commit/945fc79ba90d8532e7f14412b2caed99508b9761) and [f53c790](https://github.com/tudat-team/tudatpy/commit/f53c7903302c4a001f37be8a5ca91a153d80a231).

**Comment by gaffarelj** [comment]
This issue has been resolved by adding the `sphinx_copybutton` package to the documentation. This has been implemented in commits [945fc79](https://github.com/tudat-team/tudatpy/commit/945fc79ba90d8532e7f14412b2caed99508b9761) and [f53c790](https://github.com/tudat-team/tudatpy/commit/f53c7903302c4a001f37be8a5ca91a153d80a231).

**Comment by FilippoOggionni** [comment]
@gaffarelj one small note: there are two different conda environment files to produce the API docs. The one you modified in f53c790 is used to produce the API docs online. The other one, which is useful to produce the API docs locally, should be updated as well (I did it in commit 98b2e4a).

@jo11he thanks for noticing this! 💯 

For the record, I thought that perhaps having only one environment file would make more sense. However, due to how the API generation system is structured, I think it is unavoidable to have two different environment files because they are effectively in two different github repos (please correct me if I am wrong).
