### ISSUE TITLE
Fix exceptions raised during API docs build

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat-multidoc#22]
A high number of exceptions are raised during the API docs build, as seen [here](https://readthedocs.org/api/v2/build/15750252.txt) for example (CTRL+F for `the following exception was raised:`).

These exceptions are raised before references are made to in-exposed differently-named attributes of tudatpy.

**Comment by gaffarelj** [comment]
This has been implemented in commits 3841031635436959f03d2fa37f2fa4ffcea15a73 and [abb391b](https://github.com/tudat-team/tudatpy/commit/abb391b06af083a93d1cfc5bfe87a12c0d620a19).

The API docs are currently building. This issue will be closed if the exceptions are not raised during the new build.

**Comment by gaffarelj** [comment]
Sucess: the latest API docs build was exception-free: https://readthedocs.org/api/v2/build/15752908.txt

**Comment by DominicDirkx** [comment]
Wow, well done!

**Comment by DominicDirkx** [comment]
Wow, well done!
