### ISSUE TITLE
Info on model dependency for estimatableParameter factory functions

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-multidoc#26]
In the making of the docstrings for estimatableParameter factory functions I tried to give some info about how certain parameters depend on environment-/ acceleration-models. In some cases my knowledge was not sufficient, so I either left that out or went with some very generic formulation. 

These instances are marked by a 
`# (%!) help! `
comment in the [estimation.yam](https://github.com/tudat-team/tudat-multidoc/blob/18781c2eebf3e494bc74343b196b6f37575b5a5d/docstrings/numerical_simulation/estimation_setup/parameter.yaml#L455)l file.

I suggest @DominicDirkx to review this and add information as he sees need / fit.

**Comment by DominicDirkx** [comment]
Progress has been made, I'll post an update and some related points on Slack

**Comment by DominicDirkx** [comment]
Added/corrected
