### ISSUE TITLE
Estimation API docs review

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-multidoc#28]
I think it'd be good for somebody to review the API docs of the estimation and estimation_setup modules (and submodules), since I have been working on them by myself and another pair of eyes never hurts. 

Can be build from 
tudat --> develop
tudatpy --> develop
tudat-multidoc --> main

In the process special attention could be payed to the module description, I think they could potentially be improved...
Another aspect for special attention could be if there are any un-documented members in the modules, that were added while/after I was working on it and therefore slipped through...

I suggest @DominicDirkx and @FilippoOggionni for review of the issue.

**Comment by jo11he** [comment]
The enhanced API docs can also be found online by the beginning of next week!

**Comment by DominicDirkx** [comment]
Agreeed, I think it would be good if both Filippo and me have a look at this
