### ISSUE TITLE
Collection of small edits to make on API docs

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-multidoc#38]
- [x] member function `estimation_setup.create_parameter_set` missing function argument `parameter_settings`

- [x] class `estimation.PodInput` constructor has wrong return type and description (copy/paste error from the ConvergenceChecker)

- [x] `create_one_dimensional_vector_interpolator` parameter `data_to_interpolate` is duplicated, placed instead of `data_first_derivatives` - however, part of the parameter description fits the `data_first_derivatives`!

- [x] #41

- [x] #46

- [x] Add docstrings and API doc for `environment_setup.create_simplified_system_of_bodies()`. The description of this function is already given [here](https://github.com/tudat-team/tudat/blob/b1ce3138aec8790d1449183930a2b1cd2ae493c1/include/tudat/simulation/environment_setup/createBodies.h#L178-L186).

- [x] typo in `estimation_setup.parameter.gravitational_parameter` box on requirements (``gravitu_field``)

- [x] docs missing for enums in `estimation_setup.parameter` module, `EstimatebleParametersEnum` is not unimportant so I think we should make sure this is fixed. --> found this was a matter of renaming tudatpy name `EstimatebleParameterTypes` to a more English `EstimatableParameterTypes` and fixed that right away

**Comment by gaffarelj** [comment]
Not an error, but a very small docstring to add:

- [ ] Add docstrings and API doc for `environment_setup.create_simplified_system_of_bodies()`. The description of this function is already given [here](https://github.com/tudat-team/tudat/blob/b1ce3138aec8790d1449183930a2b1cd2ae493c1/include/tudat/simulation/environment_setup/createBodies.h#L178-L186).

**Comment by DominicDirkx** [comment]
Silly question; been a long day. Did I accidentally click these:

- [ ] Add docstrings and API doc for environment_setup.create_simplified_system_of_bodies(). The description of this function is already given [here](https://github.com/tudat-team/tudat/blob/b1ce3138aec8790d1449183930a2b1cd2ae493c1/include/tudat/simulation/environment_setup/createBodies.h#L178-L186). 

- [ ] typo in estimation_setup.parameter.gravitational_parameter box on requirements (gravitu_field)

I don't recall adding them...

**Comment by gaffarelj** [comment]
I sneakily added this a few hours ago when I changed the doc of the new `plotting.pareto_front` function. And I clicked it off the list 🙂
