### ISSUE TITLE
Request: element_conversion.spherical_to_cartesian_elementwise missing

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat-multidoc#50]
The `element_conversion.spherical_to_cartesian_elementwise()` function is missing from the API documentation (but is in my opinion quite a useful function).

**Comment by DominicDirkx** [comment]
Added in this commit:
https://github.com/tudat-team/tudat-multidoc/commit/74c20c75051a69d7137839bae54298ead634e131
