### ISSUE TITLE
Document how solar activity and cycles are implemented in TUDAT

### ISSUE THREAD

**Issue by Nosudrum** [tudat-team/tudat-multidoc#53]
It seems that currently this source is used :
https://celestrak.org/SpaceData/sw19571001.txt
with some documentation here :
https://celestrak.org/SpaceData/SpaceWx-format.php

It would be nice to add this to the documentation

**Comment by DominicDirkx** [comment]
Docstrings added in this commit:
https://github.com/tudat-team/tudat-multidoc/commit/a058455890f9ade09ce5fa8b71687c1569ef488d
