### ISSUE TITLE
Documentation for add_XXX_interface() functions

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-multidoc#6]
The user guide explicitly references the following functions, which do play an important role in the overall environment setup and which do not have an entry in the API docs yet:

environment_setup.add_aerodynamic_corefficient_interface()
environment_setup.add_raditation_pressure_interface()

These functions should be documented in https://github.com/tudat-team/tudat-multidoc/blob/main/docstrings/numerical_simulation/environment_setup/__package__.yaml

**Comment by DominicDirkx** [comment]
Entries added, build verified locally, current buiding on readthedocs:

https://readthedocs.org/projects/tudatpy/builds/
