### ISSUE TITLE
tudat-multidoc not documenting with pydantic v2.3.0

### ISSUE THREAD

**Issue by kgzenk** [tudat-team/tudat-multidoc#65]
When trying to document the current (local) version of the documentation - using either python cli d or python cli a - pydantic throws a weird error when trying to parse the initial yaml file (__package__.yaml) in the docstrings. I've attached the entire error output as a .txt file.
[pydantic_error_output.txt](https://github.com/tudat-team/tudat-multidoc/files/12766142/pydantic_error_output.txt)

**Comment by DominicDirkx** [comment]
You should be able to use this one to create the correct environment:

https://github.com/tudat-team/tudatpy/blob/master/docs/environment_readthedocs.yaml

I'll keep the issue open to correct this properly

**Comment by kgzenk** [comment]
Neither Conda nor mamba are able to successfully solve all dependency conflicts for this environment (after un-uncommenting tudat-team from the channels, otherwise nothing works, trivially)... Any ideas?

**Comment by DominicDirkx** [comment]
Could you add the full conda and mamba outputs. In the various configurations you've tried? Which OS are you on?

**Comment by kgzenk** [comment]
Sure - I've attached them here. OS-wise I work on a macOS MacBook with an Apple Silicon chip.
[conda_error_environment_readthedocs.txt](https://github.com/tudat-team/tudat-multidoc/files/12780933/conda_error_environment_readthedocs.txt)
[mamba_error_environment_readthedocs.txt](https://github.com/tudat-team/tudat-multidoc/files/12780937/mamba_error_environment_readthedocs.txt)

**Comment by DominicDirkx** [comment]
It looks like it has some issues with the basemap. Try removing it

**Comment by kgzenk** [comment]
Works!

**Comment by sbcow** [comment]
Hey team, 

I'm afraid I'm also running into this issue, however, even after removing basemap I still receive some errors related to the `__package__.yaml `when trying `python cli d` or `python cli a`. The error I get is shown below in `error.log`. I removed `basemap` and `basemap-data-hires`, and uncommented `tudat-team` as @kgzenk mentioned previously. Any suggestions?

Best,
Sean

[error.log](https://github.com/tudat-team/tudat-multidoc/files/12804174/error.log)

ps. Miss you all!

**Comment by DominicDirkx** [comment]
Hi Sean,

My apologies, I could have sworn I replied to this already! Great to see you still using Tudat :) We made a correction to the cli tool and pushed it to tudat-bundle:

https://github.com/tudat-team/tudat-bundle

it should work now,

Cheers,

Dominic

**Comment by sbcow** [comment]
Hey Dominic,

No worries! After looking at the recent change to the cli tool, it seems that the cpp API documentation was just commented out. It happens that I would like to access the C++ API documentation, not the python one. Is the C++ API documentation not working at all?

Best,
Sean

**Comment by DominicDirkx** [comment]
Hi Sean, the C++ documentation (in this new setup) has never worked properly... Since we have very few C++-'native' users, we're also seriously considering not proceeding with setting an API-docs for the C++ interface. But, be aware that the 'C++ documentation' as foreseen through moultidoc would not have anything different compared to the current setup, except proper listing of C++ types/names.
