### ISSUE TITLE
Essential docstings missing in propagation_setup.propagator

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-multidoc#7]
When going over the single arc propagation page on tudat-space I noticed that propagation_setup.propagator.translational() does not result in a valid link. I checked the API docs and saw that translational (factory function for Translational Propagator Settings) is not documented there. 
@FilippoOggionni can this be fixed? Are there possibly other undocumented FFs in this module?

**Comment by DominicDirkx** [comment]
That's odd.... I could have sworn I saw/wrote this. I'll check the commit history.

**Comment by DominicDirkx** [comment]
Fixed locally, API documentation now rebuilding
