### ISSUE TITLE
create example code snippets for various API Documentation entries

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-multidoc#8]
Actions:

- [x] environment setup:
  - [x] atmosphere (only exponential, exponential_predefined, wind, etc...)
  - [x] aerodynamic_coefficients (only custom, tabulated, tabulated_force_only, scaled)
  - [x] ephemeris
  - [x] gravity field
  - [x] radiation pressure
  - [x] rotation model 
  - [x] shape
- [ ] propagation setup:
  - [x] acceleration (only thrust_and_isp_from_custom_function missing)
  - [x] dependent variables
  - [x] integrator
  - [ ] propagator (only propagator creation - translational, rotational, etc...)
  - [x] torque
  - [x] thrust

**Comment by FilippoOggionni** [comment]
@jo11he @gaffarelj for the environment part, most modules are done, but I think for _some_ examples it would be better to provide actual values of input arguments rather than showing, e.g., `initial_state = ...`. Better to put an array with random number rather than only dots. This way, the user realizes how it can be done. For some other, instead, leaving something like  `initial_state = ...` is okay, I think it is a case-by-case choice

**Comment by gaffarelj** [comment]
I finished adding code snippets (and making other improvements) to all of the [environment_setup](https://tudatpy.readthedocs.io/en/latest/environment_setup.html) modules for the API documentation.

While at it, I also added the `AerodynamicCoefficientsIndependentVariables` class to the [environment](https://tudatpy.readthedocs.io/en/latest/environment.html) API documentation.

**Comment by DominicDirkx** [comment]
Very good! Is there any roadblock or point of discussion here, or are you good to go for the next parts? Nice to see this being extended :)

**Comment by gaffarelj** [comment]
I do not expect any struggle to add code snippets to the `propagation` and `propagation_setup` modules :)
I am however first working on exposing the time conversions, for which I only need to finish the documentation (the exposing is now done, though not pushed).

**Comment by DominicDirkx** [comment]
Added links to propagaor setup in this commit:
https://github.com/tudat-team/tudat-multidoc/commits/feature/consistent_propagation_settings
