### ISSUE TITLE
Length of weight input in estimation is not constrained by length of observation set

### ISSUE THREAD

**Issue by daanwitte99** [tudat-team/tudat-multidoc#81]
I am currently estimating space debris using optical observations (RA / Decl). Once I tried implementing a weight vector, I noticed something odd.

Say I want to estimate an orbit on 30 observations. This means I will technically have 60 observations in my observation set (30 RA, 30 Decl. observations). I accidentally used a weight vector in my estimation input that was 30 entries long, instead of 60.

This showed odd behaviour (because 60 are required in this case), LS iterations were behaving almost randomly everytime I clicked the button. But I never received an error message that my weight vector was not the right size.

It could be useful to implement a check if the weight vector is the same size as the observation set, otherwise returning an error message.

**Comment by DominicDirkx** [comment]
Corrected in latest dev version
